[package]
name = "cli-tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
itertools = "0.14.0"
tokio = { version = "1.44.0", features = ["full"] }
